#pragma once
#include <glfw3.h>

namespace dream {
	namespace input {

		enum class MouseButtons
		{
			LEFTBUTTON = GLFW_MOUSE_BUTTON_LEFT,
			RIGHTBUTTON = GLFW_MOUSE_BUTTON_RIGHT,
			MIDDLEBUTTON = GLFW_MOUSE_BUTTON_MIDDLE,
		};

		enum class KeyboardKeys
		{
			Q = GLFW_KEY_Q, W = GLFW_KEY_W, E = GLFW_KEY_E, R = GLFW_KEY_R, T = GLFW_KEY_T, Y = GLFW_KEY_Y, U = GLFW_KEY_U, I = GLFW_KEY_I, O = GLFW_KEY_O, P = GLFW_KEY_P,
			A = GLFW_KEY_A, S = GLFW_KEY_S, D = GLFW_KEY_D, F = GLFW_KEY_F, G = GLFW_KEY_G, H = GLFW_KEY_H, J = GLFW_KEY_J, K = GLFW_KEY_K, L = GLFW_KEY_L,
			Z = GLFW_KEY_Z, X = GLFW_KEY_X, C = GLFW_KEY_C, V = GLFW_KEY_V, B = GLFW_KEY_B, N = GLFW_KEY_N, M = GLFW_KEY_M,

			LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
			ESC = GLFW_KEY_ESCAPE,
			TAB = GLFW_KEY_TAB,
			LEFT_CTRL = GLFW_KEY_LEFT_CONTROL,
			LEFT_ALT = GLFW_KEY_LEFT_ALT,

			SPACE = GLFW_KEY_SPACE,
			ENTER = GLFW_KEY_ENTER,

			UP = GLFW_KEY_UP,
			DOWN = GLFW_KEY_DOWN,
			LEFT = GLFW_KEY_LEFT,
			RIGHT = GLFW_KEY_RIGHT,
		};

		enum class State 
		{			
			RELEASED = GLFW_RELEASE,
			PRESSED = GLFW_PRESS,
		};
	}
}

